from enum import Enum

class UserRole(str, Enum):
    USER = "USER"
    DOCTOR = "DOCTOR"
    ADMIN = "ADMIN"

class DoctorVerificationStatus(str, Enum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"

class TimeslotStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    BOOKED = "BOOKED"
    CANCELLED = "CANCELLED"

class AppointmentStatus(str, Enum):
    PENDING_PAYMENT = "PENDING_PAYMENT"
    CONFIRMED = "CONFIRMED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    REFUNDED = "REFUNDED"

class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    REFUNDED = "REFUNDED"

class PaymentTargetType(str, Enum):
    APPOINTMENT = "APPOINTMENT"
    PHARMACY_ORDER = "PHARMACY_ORDER"

class PaymentGateway(str, Enum):
    BKASH = "BKASH"

class OrderStatus(str, Enum):
    PENDING_PAYMENT = "PENDING_PAYMENT"
    CONFIRMED = "CONFIRMED"
    PROCESSING = "PROCESSING"
    SHIPPED = "SHIPPED"
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"

class NotificationType(str, Enum):
    APPOINTMENT_REMINDER_30MIN = "APPOINTMENT_REMINDER_30MIN"
    APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
    APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
    CONSULTATION_READY = "CONSULTATION_READY"
    ORDER_CONFIRMED = "ORDER_CONFIRMED"
    ORDER_STATUS_UPDATE = "ORDER_STATUS_UPDATE"
    SYSTEM = "SYSTEM"

class MedicineCategory(str, Enum):
    TABLET = "TABLET"
    CAPSULE = "CAPSULE"
    SYRUP = "SYRUP"
    INJECTION = "INJECTION"
    DROPS = "DROPS"
    OINTMENT = "OINTMENT"
    INHALER = "INHALER"
    HERBAL = "HERBAL"
    SURGICAL = "SURGICAL"
    OTHER = "OTHER"

class AuditAction(str, Enum):
    DOCTOR_CREATED = "DOCTOR_CREATED"
    DOCTOR_VERIFIED = "DOCTOR_VERIFIED"
    DOCTOR_REJECTED = "DOCTOR_REJECTED"
    DOCTOR_ACTIVATED = "DOCTOR_ACTIVATED"
    DOCTOR_DEACTIVATED = "DOCTOR_DEACTIVATED"
    APPOINTMENT_BOOKED = "APPOINTMENT_BOOKED"
    APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
    APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
    CONSULTATION_COMPLETED = "CONSULTATION_COMPLETED"
    PAYMENT_INITIATED = "PAYMENT_INITIATED"
    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    PAYMENT_REFUNDED = "PAYMENT_REFUNDED"
    ORDER_PLACED = "ORDER_PLACED"
    ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED"
    PLATFORM_FEE_UPDATED = "PLATFORM_FEE_UPDATED"
