from enum import Enum

class UserRole(str, Enum):
    USER = "USER"
    DOCTOR = "DOCTOR"
    NURSE = "NURSE"
    ADMIN = "ADMIN"

class DoctorVerificationStatus(str, Enum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"

class TimeslotStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    BOOKED = "BOOKED"
    CANCELLED = "CANCELLED"

class AppointmentStatus(str, Enum):
    PENDING_PAYMENT = "PENDING_PAYMENT"
    CONFIRMED = "CONFIRMED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    REFUNDED = "REFUNDED"

class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    REFUNDED = "REFUNDED"

class PaymentTargetType(str, Enum):
    APPOINTMENT = "APPOINTMENT"
    PHARMACY_ORDER = "PHARMACY_ORDER"

class PaymentGateway(str, Enum):
    BKASH = "BKASH"

class OrderStatus(str, Enum):
    PENDING_PAYMENT = "PENDING_PAYMENT"
    CONFIRMED = "CONFIRMED"
    PROCESSING = "PROCESSING"
    SHIPPED = "SHIPPED"
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"

class NotificationType(str, Enum):
    APPOINTMENT_REMINDER_30MIN = "APPOINTMENT_REMINDER_30MIN"
    APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
    APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
    CONSULTATION_READY = "CONSULTATION_READY"
    ORDER_CONFIRMED = "ORDER_CONFIRMED"
    ORDER_STATUS_UPDATE = "ORDER_STATUS_UPDATE"
    SYSTEM = "SYSTEM"

class MedicineCategory(str, Enum):
    TABLET = "TABLET"
    CAPSULE = "CAPSULE"
    SYRUP = "SYRUP"
    INJECTION = "INJECTION"
    DROPS = "DROPS"
    OINTMENT = "OINTMENT"
    INHALER = "INHALER"
    HERBAL = "HERBAL"
    SURGICAL = "SURGICAL"
    OTHER = "OTHER"

class AuditAction(str, Enum):
    # Auth
    USER_REGISTERED = "USER_REGISTERED"
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"
    USER_ACTIVATED = "USER_ACTIVATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    USER_LOGIN = "USER_LOGIN"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    PASSWORD_RESET = "PASSWORD_RESET"

    # User & Doctor Profiles
    USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED"
    DOCTOR_PROFILE_UPDATED = "DOCTOR_PROFILE_UPDATED"
    DOCTOR_CREATED = "DOCTOR_CREATED"
    DOCTOR_UPDATED = "DOCTOR_UPDATED"
    DOCTOR_DELETED = "DOCTOR_DELETED"
    DOCTOR_VERIFIED = "DOCTOR_VERIFIED"
    DOCTOR_REJECTED = "DOCTOR_REJECTED"
    DOCTOR_ACTIVATED = "DOCTOR_ACTIVATED"
    DOCTOR_DEACTIVATED = "DOCTOR_DEACTIVATED"
    TIMESLOTS_CREATED = "TIMESLOTS_CREATED"
    TIMESLOT_DELETED = "TIMESLOT_DELETED"

    # Telemedicine & Consultations
    APPOINTMENT_BOOKED = "APPOINTMENT_BOOKED"
    APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
    APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
    VIDEO_ROOM_TOKEN_ISSUED = "VIDEO_ROOM_TOKEN_ISSUED"
    CONSULTATION_COMPLETED = "CONSULTATION_COMPLETED"

    # Payments
    PAYMENT_INITIATED = "PAYMENT_INITIATED"
    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    PAYMENT_REFUNDED = "PAYMENT_REFUNDED"

    # Pharmacy & Orders
    MEDICINE_CREATED = "MEDICINE_CREATED"
    MEDICINE_UPDATED = "MEDICINE_UPDATED"
    MEDICINE_DELETED = "MEDICINE_DELETED"
    MEDICINES_BULK_DELETED = "MEDICINES_BULK_DELETED"
    MEDEASY_INGESTION_TRIGGERED = "MEDEASY_INGESTION_TRIGGERED"
    ORDER_PLACED = "ORDER_PLACED"
    ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED"
    PLATFORM_FEE_UPDATED = "PLATFORM_FEE_UPDATED"
    SETTINGS_UPDATED = "SETTINGS_UPDATED"

    # Media
    MEDIA_UPLOADED = "MEDIA_UPLOADED"
    MEDIA_DELETED = "MEDIA_DELETED"
